# Generated by Django 4.0.4 on 2022-04-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_image_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default='url', max_length=222),
        ),
    ]
